### ISSUE TITLE
What is the use case of raw property in ast?

### ISSUE THREAD

**Issue by hulkish** [vtrushin/json-to-ast#23]
I wonder, because it seems a bit like it was probably used for testing the parser? If it's just a repeat of 
 `value`, maybe better to remove it?

**Comment by hulkish** [comment]
@vtrushin I see, so in theory we could just keep `raw` instead of value?

**Comment by vtrushin** [comment]
@hulkish There is no bad to give user to avoid these additional manipulations. It's usual format for ast node. Look here other parsers' code: https://astexplorer.net/

**Comment by hulkish** [comment]
@vtrushin fair enough, thanks for explaining!

**Comment by vtrushin** [comment]
@hulkish Thanks you!
