### ISSUE TITLE
2.0.5 breaks backward capabilities

### ISSUE THREAD

**Issue by lahmatiy** [vtrushin/json-to-ast#24]
2.0.5 release changed target node version to 6, so resulting source code is not transforming to es5 anymore. However, `json-to-ast` is using by projects that support node.js below 6, in particular `css-tree` which test is failing now. It's a bad practice to change env support in a patch version, so instead of `2.0.5` there should be `3.0.0`.

**Comment by vtrushin** [comment]
https://github.com/vtrushin/json-to-ast/releases/tag/v2.0.6

**Comment by vtrushin** [comment]
https://github.com/vtrushin/json-to-ast/releases/tag/v2.0.7
