### ISSUE TITLE
Add support for emoji and other special characters on the unexpected symbol error message

### ISSUE THREAD

**Issue by bsonntag** [vtrushin/json-to-ast#25]
When an unexpected symbol error occurs at an emoji character, the resulting error message doesn't display the correct character.

```js
try {
  jsonToAst('💩');
} catch (error) {
  console.log(error.rawMessage);
  // > "Unexpected symbol <�> at 1:1"
}
```

To be clear, I was expecting to see the following error message: `Unexpected symbol <💩> at 1:1`.

From what I can gather, this happens because [`String.prototype.charAt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charAt) (which is being used to get the offending character) doesn't support these special characters.

Example here: https://runkit.com/bsonntag/5c1b96384702bf0012a73396

**Comment by vtrushin** [comment]
Fixed. https://github.com/vtrushin/json-to-ast/releases/tag/v2.1.0

**Comment by vtrushin** [comment]
https://runkit.com/embed/kz13b3t143nn

**Comment by kien-kreate** [comment]
From my user viewpoint, I would prefer using v2.0.7. Reasons:

- JSON specification does not mention grapheme. A character in JSON spec corresponds to a code point: https://www.json.org/json-en.html
- v2.0.10 is three times as big as v2.0.7: https://bundlephobia.com/package/json-to-ast@2.1.0

Personally, `"Unexpected symbol <�> at 1:1"` is totally fine.
