### ISSUE TITLE
Is there any way to go back to json after it's converted to ast？

### ISSUE THREAD

**Issue by heiyehk** [vtrushin/json-to-ast#26]
Hi! @vtrushin .
I've used it in my project, but it's a little unclear how to convert it back to json after the ast changes.

**Comment by heiyehk** [comment]
@vtrushin .Please forgive me if I am not good at expressing myself. I think my ability is not very good. I'm sorry.

**Comment by vtrushin** [comment]
Hi @heiyehk! Would you mind to describe  what exactly you 're using parser for?

**Comment by heiyehk** [comment]
@vtrushin 
When I get the contents of a json file through nodejs, I parse the json into an ast using json-to-ast, and after modifying the contents, how do I get it back to the json text?


Emmmm, I am Chinese, but my English is not very good, please forgive me

**Comment by vtrushin** [comment]
Please, don't worry. My native language is Russian. And I also speak English badly.

I think using `JSON.parse` and `JSON.stringify` javascript build-ins instead of this package will be enough for you. I see no reason to edit JSON with this package

**Comment by heiyehk** [comment]
Aha ha ha, yes, I am a vegetable chicken, thank you very much. Ok, it's time for me to get off work

**Comment by vtrushin** [comment]
Have a nice evening! )
